server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.153.129:3306/hospital?characterEncoding=UTF-8&&useSSL=false
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.153.129:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: service-hospital
  profiles:
    active: dev
logging:
  level:
    root: warn

