server:
  port: 80
spring:
  main:
    web-application-type: reactive
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: service-dict
        uri: lb://service-dict
        predicates: Path=/*/dict/**
      routes[1]:
        id: service-hospital
        uri: lb://service-hospital
        predicates: Path=/*/hosp/**
      routes[2]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**
      routes[3]:
        id: service-msm
        uri: lb://service-msm
        predicates: Path=/*/msm/**
