server:
  port: 8004
spring:
  application:
    name: service-msm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.153.129
    port: 6379
    password: 123456
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI5tEytYriA3AjdQXUhVcD
    secret: 9a3eFvj3o360rwdsGYnUOAt07KooU7
